spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/quanxian-demo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
mybatis:
  mapper-locations: classpath:/mapper/*
  configuration:
    mapUnderscoreToCamelCase: true

server:
  port: 8080

